<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rb_04_mandiri_kartu_kredit</name>
   <tag></tag>
   <elementGuidId>ee06f209-35ac-4b40-b37c-246a19e60e27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/section/div[1]/div[2]/div[1]/div[2]/ul/div[2]/li[1]/ul/li[3]/label[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>veritrans_mandiri</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/section/div[1]/div[2]/div[1]/div[2]/ul/div[2]/li[1]/ul/li[3]/label[1]</value>
   </webElementProperties>
</WebElementEntity>
