<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rb_12_BRI_Kartu_Kredit</name>
   <tag></tag>
   <elementGuidId>85f93f4e-7d60-4f02-a5dd-a232d38cb809</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/section/div[1]/div[2]/div[1]/div[2]/ul/div[2]/li[3]/ul/li[3]/label[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>bca_creditcard_bri_cc</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/section/div[1]/div[2]/div[1]/div[2]/ul/div[2]/li[3]/ul/li[3]/label[1]</value>
   </webElementProperties>
</WebElementEntity>
