<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rb_14_BTN_Debit_Online</name>
   <tag></tag>
   <elementGuidId>15d65be8-91b7-42e7-b662-c64e564c0f42</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>debit_online_btn</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/section[1]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;container940 clearfix choose-payment&quot;]/div[@class=&quot;full-content&quot;]/div[@class=&quot;container-white mt20&quot;]/ul[@class=&quot;payment-list border-container pt0 clearfix&quot;]/div[@class=&quot;clearfix&quot;]/li[@class=&quot;pl&quot;]/ul[@class=&quot;payment-option&quot;]/li[2]/label[1]</value>
   </webElementProperties>
</WebElementEntity>
