<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rb_30_BRI_Kartu_Kredit_Cicilan</name>
   <tag></tag>
   <elementGuidId>946273ea-42de-41e7-83ae-bbdb74bacd7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/section/div[1]/div[2]/div[1]/div[2]/ul/div[2]/li[3]/ul/li[4]/label[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/section/div[1]/div[2]/div[1]/div[2]/ul/div[2]/li[3]/ul/li[4]/label[1]</value>
   </webElementProperties>
</WebElementEntity>
