<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Nomor_HP_TembakURL</name>
   <tag></tag>
   <elementGuidId>0d0670a8-c364-42ab-a765-5988dff49ac7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/section/section[2]/div/div[1]/div[2]/div[1]/form/div[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/section/section[2]/div/div[1]/div[2]/div[1]/form/div[2]/input</value>
   </webElementProperties>
</WebElementEntity>
