<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Oranye</name>
   <tag></tag>
   <elementGuidId>6219be89-20b7-4c9e-8eb6-6e4b2e8c1c6e</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Oranye</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;clearfix&quot;]/div[@class=&quot;bgColor-white&quot;]/div[@class=&quot;wrapper-pdp pt30 pb30 clearfix&quot;]/section[@class=&quot;main-content fLeft&quot;]/div[@class=&quot;clearfix&quot;]/div[@class=&quot;product-info fRight&quot;]/div[@class=&quot;product-detail mt10 pb15 width-full&quot;]/div[@class=&quot;product-line clearfix&quot;]/ul[@class=&quot;sku-type  sku-img  fLeft pRelative&quot;]/li[@class=&quot;tAlign-center&quot;]/a[1]/span[1]</value>
   </webElementProperties>
</WebElementEntity>
